# Generated by Django 5.0 on 2023-12-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eye_Sight_Detect_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='added_by_id',
            new_name='added_by',
        ),
    ]
