# Generated by Django 5.0 on 2023-12-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eye_Sight_Detect_app', '0002_rename_added_by_id_patient_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='added_by',
            new_name='added_by_id',
        ),
    ]
