# Generated by Django 5.0 on 2024-01-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eye_Sight_Detect_app', '0004_patient_left_eye_result_patient_right_eye_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyesightdetact_model', models.CharField(max_length=255)),
            ],
        ),
    ]
