# Generated by Django 5.0 on 2024-01-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eye_Sight_Detect_app', '0005_deeplearningmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeepLearningModel',
        ),
    ]
